from __future__ import annotations

TEMPLATE_PRIMARY_PATTERNS = {
    "template-research-source-grounded-brief": "pattern-evidence-table",
    "template-research-competing-claims": "pattern-source-hierarchy",
    "template-research-paper-reading": "pattern-evidence-table",
    "template-code-agent-repo-change": "pattern-agent-state-ledger",
    "template-code-review-findings": "pattern-rubric-first-evaluation",
    "template-ci-failure-triage": "pattern-retry-with-diagnosis",
    "template-data-schema-extraction": "pattern-output-schema",
    "template-doc-comparison": "pattern-evidence-table",
    "template-transcript-action-summary": "pattern-agent-state-ledger",
    "template-business-decision-memo": "pattern-rubric-first-evaluation",
    "template-business-risk-register": "pattern-rubric-first-evaluation",
    "template-product-experiment-plan": "pattern-rubric-first-evaluation",
    "template-writing-audience-rewrite": "pattern-objective-contract",
    "template-writing-technical-explainer": "pattern-objective-contract",
    "template-support-response": "pattern-clarify-or-proceed",
    "template-agent-tool-policy": "pattern-tool-selection",
    "template-agent-handoff-summary": "pattern-agent-state-ledger",
    "template-agent-delegation-brief": "pattern-delegation-contract",
    "template-rag-answer-policy": "pattern-source-hierarchy",
    "template-security-injection-review": "pattern-defensive-injection-check",
    "template-security-tool-abuse-check": "pattern-human-approval",
    "template-security-secret-exposure": "pattern-human-approval",
    "template-multimodal-image-inspection": "pattern-multimodal-observation-first",
    "template-multimodal-chart-qa": "pattern-multimodal-observation-first",
    "template-multimodal-image-brief": "pattern-accessible-visual-brief",
    "template-provider-portability-check": "pattern-cross-model-eval",
    "template-production-prompt-change": "pattern-production-change-log",
    "template-production-cost-review": "pattern-cost-latency-budget",
}

TEMPLATE_ALLOWED_SUPPORTING_PATTERNS = {
    "template-research-source-grounded-brief": {
        "pattern-source-hierarchy",
        "pattern-abstention-rule",
    },
    "template-research-competing-claims": {"pattern-evidence-table"},
    "template-research-paper-reading": {"pattern-source-hierarchy"},
    "template-code-agent-repo-change": {
        "pattern-human-approval",
        "pattern-regression-case",
    },
    "template-code-review-findings": {"pattern-evidence-table"},
    "template-ci-failure-triage": {"pattern-regression-case"},
    "template-data-schema-extraction": {"pattern-abstention-rule"},
    "template-doc-comparison": {"pattern-source-hierarchy"},
    "template-transcript-action-summary": {"pattern-context-compression"},
    "template-business-decision-memo": {"pattern-evidence-table"},
    "template-business-risk-register": {"pattern-counterexample-guard"},
    "template-product-experiment-plan": {"pattern-regression-case"},
    "template-writing-audience-rewrite": {"pattern-context-boundary"},
    "template-writing-technical-explainer": {"pattern-source-hierarchy"},
    "template-support-response": {"pattern-objective-contract"},
    "template-agent-tool-policy": {"pattern-human-approval"},
    "template-agent-handoff-summary": {"pattern-context-compression"},
    "template-agent-delegation-brief": {"pattern-human-approval"},
    "template-rag-answer-policy": {
        "pattern-abstention-rule",
        "pattern-defensive-injection-check",
    },
    "template-security-injection-review": {"pattern-context-boundary"},
    "template-security-tool-abuse-check": {
        "pattern-tool-selection",
        "pattern-secure-output-validation",
    },
    "template-security-secret-exposure": {
        "pattern-secure-output-validation",
        "pattern-production-change-log",
    },
    "template-multimodal-image-inspection": {"pattern-abstention-rule"},
    "template-multimodal-chart-qa": {"pattern-evidence-table"},
    "template-multimodal-image-brief": {"pattern-objective-contract"},
    "template-provider-portability-check": {"pattern-regression-case"},
    "template-production-prompt-change": {
        "pattern-regression-case",
        "pattern-human-approval",
    },
    "template-production-cost-review": {"pattern-rubric-first-evaluation"},
}

TEMPLATE_PRIMARY_LESSONS = {
    "template-research-source-grounded-brief": "04-grounding-and-long-context",
    "template-research-competing-claims": "04-grounding-and-long-context",
    "template-research-paper-reading": "04-grounding-and-long-context",
    "template-code-agent-repo-change": "07-agents-and-tools",
    "template-code-review-findings": "06-evaluation",
    "template-ci-failure-triage": "11-production-operations",
    "template-data-schema-extraction": "05-structured-outputs",
    "template-doc-comparison": "04-grounding-and-long-context",
    "template-transcript-action-summary": "08-context-engineering",
    "template-business-decision-memo": "06-evaluation",
    "template-business-risk-register": "06-evaluation",
    "template-product-experiment-plan": "06-evaluation",
    "template-writing-audience-rewrite": "02-prompt-anatomy",
    "template-writing-technical-explainer": "02-prompt-anatomy",
    "template-support-response": "03-core-techniques",
    "template-agent-tool-policy": "07-agents-and-tools",
    "template-agent-handoff-summary": "08-context-engineering",
    "template-agent-delegation-brief": "07-agents-and-tools",
    "template-rag-answer-policy": "04-grounding-and-long-context",
    "template-security-injection-review": "09-security",
    "template-security-tool-abuse-check": "09-security",
    "template-security-secret-exposure": "09-security",
    "template-multimodal-image-inspection": "10-multimodal",
    "template-multimodal-chart-qa": "10-multimodal",
    "template-multimodal-image-brief": "10-multimodal",
    "template-provider-portability-check": "06-evaluation",
    "template-production-prompt-change": "11-production-operations",
    "template-production-cost-review": "11-production-operations",
}

TEMPLATE_ALLOWED_RELATED_LESSONS = {
    "template-research-source-grounded-brief": {"06-evaluation"},
    "template-research-competing-claims": {"06-evaluation"},
    "template-research-paper-reading": {"06-evaluation"},
    "template-code-agent-repo-change": {"11-production-operations"},
    "template-code-review-findings": {"11-production-operations"},
    "template-ci-failure-triage": {"07-agents-and-tools"},
    "template-data-schema-extraction": set(),
    "template-doc-comparison": {"05-structured-outputs"},
    "template-transcript-action-summary": {"07-agents-and-tools"},
    "template-business-decision-memo": {"11-production-operations"},
    "template-business-risk-register": {"11-production-operations"},
    "template-product-experiment-plan": {"11-production-operations"},
    "template-writing-audience-rewrite": set(),
    "template-writing-technical-explainer": {"04-grounding-and-long-context"},
    "template-support-response": set(),
    "template-agent-tool-policy": {"09-security"},
    "template-agent-handoff-summary": {"07-agents-and-tools"},
    "template-agent-delegation-brief": {"09-security"},
    "template-rag-answer-policy": {"09-security"},
    "template-security-injection-review": {"08-context-engineering"},
    "template-security-tool-abuse-check": {"07-agents-and-tools"},
    "template-security-secret-exposure": {"11-production-operations"},
    "template-multimodal-image-inspection": set(),
    "template-multimodal-chart-qa": {"06-evaluation"},
    "template-multimodal-image-brief": {"02-prompt-anatomy"},
    "template-provider-portability-check": {"11-production-operations"},
    "template-production-prompt-change": {"06-evaluation"},
    "template-production-cost-review": {"06-evaluation"},
}
